### ISSUE TITLE
RQRCode::QRCodeRunTimeError (code length overflow. (1004>976). (Try a larger size!)):

### ISSUE THREAD

**Issue by akhilesharora** [whomwah/rqrcode#61]
Fails for user on prod after migration sometimes. If I check the Ignore2FA then it works else doesn't.
```
Processing by AccountController#login as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"5OrvYz8T87xZgpT57Kpt2MxhSL2UgRgCvxAUsrvR8T+Ym7AH1Kdu5/AB8g9f8JDMu6fBCT94kI2wLLW3oGPzEw==", "username"=>"admin", "password"=>"[FILTERED]", "login"=>"Login"}
  Current user: anonymous
Completed 500 Internal Server Error in 13ms (ActiveRecord: 8.0ms)

RQRCode::QRCodeRunTimeError (code length overflow. (1004>976). (Try a larger size!)):
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:11:in `new'
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_init.rb:11:in `password_authentication'
  plugins/redmine_2fa/lib/redmine_2fa/patches/account_controller_patch/second_authentication_prepare.rb:16:in `password_authentication'
  app/controllers/account_controller.rb:205:in `authenticate_user'
  app/controllers/account_controller.rb:38:in `login'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by bjornblomqvist** [comment]
The problem is that the text you are trying to include in the qrcode cant fit. As the error suggests try a larger size.

BR Björn
